# Generated by Django 2.1.1 on 2018-11-05 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Case', '0002_caseoverview_datecreated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseoverview',
            name='dateCreated',
            field=models.DateTimeField(),
        ),
    ]
