# Generated by Django 2.1.1 on 2018-11-06 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Case', '0003_auto_20181105_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseoverview',
            name='dateCreated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
